max_completion_length: 512
max_draft_length: 256
max_prompt_length: 3000
max_steps: 400
num_generations: <your_num_generations>
per_device_train_batch_size: <your_per_device_train_batch_size>
gradient_accumulation_steps: <your_gradient_accumulation_steps>
max_turn: 10
temperature: 0.7
top_p: 0.95
max_tokens: 1500
window_size: 5
db_format: create_sql
vs_format: detailed_json
action_format: markdown
output_format: json
method: neusym_rag
interact_protocol: react
dataset_name: airqa
db: ai_research
database_dir: data/database/ai_research/
db_type: duckdb
vectorstore: ${db}
launch_method: standalone
docker_uri: http://127.0.0.1:19530
vectorstore_dir: data/vectorstore/ai_research/
test_data: <your_test_data>
name: gpt-4o-mini
model_name_or_path: <your_model_name_or_path>
save_strategy: steps
report_to: tensorboard
save_steps: 100
output_dir: <your_output_dir>
logging_dir: <your_logging_dir>
logging_steps: 1
max_grad_norm : 10.0
num_iterations: 5
epsilon_high: 0.28
