### model
model_name_or_path: ../../models/Qwen2.5-3B-Instruct

### method
stage: sft
do_train: true
finetuning_type: lora
lora_target: all
lora_rank: 16
lora_alpha: 16
lora_dropout: 0.05

### dataset
dataset: airqa_h10000_draft
template: qwen
cutoff_len: 4096
overwrite_cache: true
preprocessing_num_workers: 16
mask_history: true

### output
output_dir: saves/qwen2.5-3b_h10000_draft/lora/sft
logging_steps: 1
save_steps: 200
plot_loss: true
overwrite_output_dir: true

### train
per_device_train_batch_size: 1
gradient_accumulation_steps: 16
learning_rate: 1.0e-4
num_train_epochs: 1.0
lr_scheduler_type: cosine
warmup_ratio: 0.1
bf16: true
ddp_timeout: 180000000

### eval
val_size: 0.05
per_device_eval_batch_size: 1
eval_strategy: steps
eval_steps: 25
